### ISSUE TITLE
大佬看看这是啥

### ISSUE THREAD

**Issue by xinkeji** [gavinblog/blog-anzhiyu#1]
ERROR Script load failed: scripts/helpers/charts.js
ReferenceError: document is not defined
    at /home/runner/work/blog-anzhiyu/blog-anzhiyu/scripts/helpers/charts.js:447:1
一定需要这个js嘛

**Comment by geekswg** [comment]
这是统计页面用到的图表相关js，如果你不需要这个页面就可以删掉。
[https://hexo.geekswg.top/charts/](https://hexo.geekswg.top/charts/)

**Comment by geekswg** [comment]
这个报错好像不影响正常运行，如果有强迫症的话，就删了把。

**Comment by xinkeji** [comment]
好的谢谢

**Comment by bigdata-yx** [comment]
INFO  Validating config
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Nunjucks Error: _posts/demo/demo-anzhiyu/index.md [Line 5, Column 155] unknown block tag: tabs
    =====               Context Dump               =====
    === (line number probably different from source) ===
  1 | <h2 id="主题图标"><a href="#主题图标" class="headerlink" title="主题图标"></a>主题图标</h2><p><a href="https://www.iconfont.cn/collections/detail?cid=44481">anzhiyu-icon</a></p>
  2 | <blockquote>
  3 | <p>标签外挂是 Hexo 独有的功能，并不是标准的 Markdown 格式。 以下的写法，只适用于 AnZhiYu 主题，用在其它主题上不会 有效果，甚至可能会报错。使用前请留意</p>
  4 | </blockquote>
  5 | <h2 id="Note-Bootstrap-Callout"><a href="#Note-Bootstrap-Callout" class="headerlink" title="Note (Bootstrap Callout)"></a>Note (Bootstrap Callout)</h2>{% tabs tab-note %}
  6 |
  7 | 
  8 |
  9 | 
  10 |
    =====             Context Dump Ends            =====
    at formatNunjucksError (E:\blog\blog-anzhiyu-master\node_modules\hexo\lib\extend\tag.js:173:13)
    at E:\blog\blog-anzhiyu-master\node_modules\hexo\lib\extend\tag.js:249:29
    at tryCatcher (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (E:\blog\blog-anzhiyu-master\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)
    大佬这个啥问题
